%% DEMO_PRETRAINING
%
% Training MDNet models.
%
% Hyeonseob Nam, 2015
%

clear;

% Prepare a CNN model for learning MDNet.
mdnet_prepare_model;

%% Training MDNet using the sequences from {VOT13,14,15}-{OTB100}
% for experiments on OTB
mdnet_pretrain('seqsList',...
    {struct('dataset','vot2016','list','pretraining/seqList/vot16.txt'),...
   struct('dataset','vot2015','list','pretraining/seqList/vot15.txt'),...
   struct('dataset','vot2013','list','pretraining/seqList/vot13.txt'),...
   struct('dataset','vot2014','list','pretraining/seqList/vot14.txt'),...
    struct('dataset','otb','list','pretraining/seqList/otb.txt')},...
    'outFile', fullfile('models','M-SPN1.0.mat'),...
    'roiDir', fullfile('models','M-SPN_data_1.0'));

%% Training MDNet using the sequences from {OTB}-{VOT14}
% for experiments on VOT14
% mdnet_pretrain('seqsList',...
%     {struct('dataset','otb','list','pretraining/seqList/otb-vot14.txt')},...
%     'outFile', fullfile('models','mdnet_otb-vot14_new.mat'),...
%     'roiDir', fullfile('models','data_otb-vot14'));

%% Training MDNet using the sequences from {OTB}-{VOT15}
% for experiments on VOT16
% mdnet_pretrain('seqsList',...
%     {struct('dataset','vot2016','list','pretraining/seqList/vot16.txt'),...
%     struct('dataset','otb','list','pretraining/seqList/otb.txt'),...
%    struct('dataset','vot2015','list','pretraining/seqList/vot15.txt'),...
%    struct('dataset','vot2014','list','pretraining/seqList/vot14.txt')},...
%     'outFile', fullfile('models','mdnet_RMCC2.0.mat'),...
%     'roiDir', fullfile('models','data_vot162.0_all'));
